inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*
    - gemfiles/*
    - spec/dummy/**/*
    - vendor/**/*
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

RSpec/ExampleLength:
  Max: 20

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  # Default is 3
  Max: 6

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
